name: Testing taskiq-aio-pika

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        cmd: ["ruff", "ty"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: 3.11
          version: "latest"
          python-version: 3.11
      - name: Install deps
        run: uv sync --all-extras
      - name: Run lint check
        run: uv run prek run -a ${{ matrix.cmd }}
  pytest:
    services:
      rabbit:
        image: heidiks/rabbitmq-delayed-message-exchange:latest
        env:
          RABBITMQ_DEFAULT_USER: "guest"
          RABBITMQ_DEFAULT_PASS: "guest"
          RABBITMQ_DEFAULT_VHOST: "/"
        options: >-
          --health-cmd="rabbitmq-diagnostics check_running -q"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=8
        ports:
          - 5672:5672
    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.py_version }}
          version: "latest"
          python-version: ${{ matrix.py_version }}
      - name: Install deps
        run: uv sync --all-extras
      - name: Run pytest check
        run: uv run pytest -vv -n auto --cov="taskiq_aio_pika" .
